# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  [push, pull_request,workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      #Environment variables usable throughout the "build" job, e.g. in OS-level commands
      
      # ** FOR GENERAL USE, LIKELY NEED TO CHANGE **
      package: isc.codetidy
      container_image: intersystemsdc/iris-community:latest
      
      # ** FOR GENERAL USE, MAY NEED TO CHANGE **
      build_flags: -dev -verbose
      test_package: UnitTest
      
      # ** FOR GENERAL USE, SHOULD NOT NEED TO CHANGE **
      instance: iris
      # Note: test_reports value is duplicated in test_flags environment variable
      test_reports: test-reports
      test_flags: >-
        -verbose -DUnitTest.ManagerClass=TestCoverage.Manager -DUnitTest.JUnitOutput=/test-reports/junit.xml
        -DUnitTest.FailuresAreFatal=1 -DUnitTest.Manager=TestCoverage.Manager
        -DUnitTest.UserParam.CoverageReportClass=TestCoverage.Report.Cobertura.ReportGenerator
        -DUnitTest.UserParam.CoverageReportFile=/source/coverage.xml
      

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      

      - name: Run Container
        run: |
          # Create test_reports directory to share test results before running container
          mkdir $test_reports
          chmod 777 $test_reports
          
          # Run InterSystems IRIS Instance
          docker pull $container_image
          docker run -d -h $instance --name $instance -v $GITHUB_WORKSPACE:/source:rw -v $GITHUB_WORKSPACE/$test_reports:/$test_reports --init $container_image
          echo halt > wait
          # Wait for instance to be ready
          until docker exec --interactive $instance iris session $instance < wait; do sleep 1; done

      - name: Install TestCoverage
        run: |
          echo "zpm \"install testcoverage\":1:1" > install-testcoverage
          docker exec --interactive $instance iris session $instance -B < install-testcoverage
          # WOrkaround for permissions issues in TestCoverage (creating directory for source export)
          chmod 777 $GITHUB_WORKSPACE
          chmod -R 777 $GITHUB_WORKSPACE/tests/_reference/compare
          
          
      - name: Build and Test
        run: |
          # Run build
          echo "zpm \"load /source $build_flags\":1:1" > build
          # Test package is compiled first as a workaround for some dependency issues.
          echo "do \$System.OBJ.CompilePackage(\"$test_package\",\"ckd\") " > test
          # Run tests
          echo "set ^%oddEnv(\"callererrorinfo\") = 2"
          echo "zpm \"$package test -only $test_flags\":1:1" >> test
          docker exec --interactive $instance iris session $instance -B < build && docker exec --interactive $instance iris session $instance -B < test &&bash <(curl -s https://codecov.io/bash)
          
      - name: XUnit Viewer
        id: xunit-viewer
        uses: AutoModality/action-xunit-viewer@v1
        if: always()
        with:
          # With -DUnitTest.FailuresAreFatal=1 a failed unit test will fail the build before this point.
          # This action would otherwise misinterpret our xUnit style output and fail the build even if
          # all tests passed.
          fail: false
      - name: Attach the report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ steps.xunit-viewer.outputs.report-name }}
          path: ${{ steps.xunit-viewer.outputs.report-dir }}
          
          
